###############################################  ADMIN TOKEN TOKEN TOKEN OK OK OK    0

#### Admin API --> TOKEN TOKEN TOKEN ---- OK OK OK
POST https://v02.medintl.info/admin-api
Content-Type: application/json

{
  "query": "mutation Login { authenticate(input: { native: { username: \"superadmin\", password: \"superadmin\" } }) { ... on CurrentUser { id identifier } } }"
}

###############################################  ADMIN TOKEN TOKEN TOKEN OK OK OK    0

### Variables
@baseUrl = https://v02.medintl.info/admin-api
@authToken = 14d9100ffd3aa07f115ef32f293e82156b1e3108051d5918175a4c89fd28a902

### 1. Sync All Products
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{authToken}}
X-Allow-Self-Signed-Certificates: true

{
  "query": "mutation SyncAllProducts { syncAllEntitiesToCms(entityType: \"Product\") { success totalEntities successCount errorCount message errors { entityId error } } }"
}

###

### 2. Sync All Variants
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "query": "mutation SyncAllVariants { syncAllEntitiesToCms(entityType: \"ProductVariant\") { success totalEntities successCount message } }"
}

