# collectionProductSummary
# 5ff6ddbc08a0c6dc630e1c1c9a174f016fc367a13aa1bed3d97da7180868a6d9

###############################################  Shop TOKEN TOKEN TOKEN OK OK OK

POST http://192.168.0.51:3000/shop-api
Content-Type: application/json

{
  "query": "mutation Login { authenticate(input: { native: { username: \"tprice@163.com\", password: \"tttttttt\" } }) { ... on CurrentUser { id identifier } } }"
}

###############################################  Shop TOKEN TOKEN TOKEN OK OK OK




POST http://192.168.0.53:3000/shop-api
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="operations"

{ 
  "query": "mutation ($file: Upload!) { uploadCustomerFile(file: $file) { id name preview source } }", 
  "variables": { "file": null } 
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="map"

{ "0": ["variables.file"] }
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="0"; filename="logo-48-48.png"
Content-Type: image/png

< /home/coding/vuestore-trae/public/logo-48-48.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--



#################################


































### Fetch product summaries for a collection (with pagination)
POST http://192.168.0.53:3000/shop-api
Content-Type: application/json
Authorization: Bearer 5ff6ddbc08a0c6dc630e1c1c9a174f016fc367a13aa1bed3d97da7180868a6d9

{
  "query": "query GetCollectionProductSummary($collectionId: ID!, $skip: Int, $take: Int) { collectionProductSummary(collectionId: $collectionId, skip: $skip, take: $take) { productId productName slug description featuredAsset { id preview } variantCount minPrice maxPrice minPriceWithTax maxPriceWithTax facetValues { id name } } }",
  "variables": {
    "collectionId": "2",
    "skip": 0,
    "take": 40
  }
}