###############################################  Shop TOKEN TOKEN TOKEN OK OK OK  1

POST http://192.168.0.53:3000/shop-api
Content-Type: application/json

{
  "query": "mutation Login { authenticate(input: { native: { username: \"tprice@163.com\", password: \"tttttttt\" } }) { ... on CurrentUser { id identifier } } }"
}

###############################################  Shop TOKEN TOKEN TOKEN OK OK OK  1


###############################################  ADMIN TOKEN TOKEN TOKEN OK OK OK 0
@host=http://192.168.0.53:3000

# 6bc5c430f597bdeb08f2e43e2398cadec31c86296d768dbce246835a0f56c82f

#### Admin API --> TOKEN TOKEN TOKEN ---- OK OK OK
POST http://192.168.0.53:3000/admin-api
Content-Type: application/json

{
  "query": "mutation Login { authenticate(input: { native: { username: \"superadmin\", password: \"superadmin\" } }) { ... on CurrentUser { id identifier } } }"
}

###############################################  ADMIN TOKEN TOKEN TOKEN OK OK OK 0


### Get all product slugs
POST http://192.168.0.53:3000/shop-api
Content-Type: application/json

{
  "query": "query GetAllProductSlugs { products(options: { take: 100 }) { items { slug } totalItems } }"
}

###

### Page 1
POST http://192.168.0.53:3000/shop-api
Content-Type: application/json

{
  "query": "query GetProductSlugsPage1 { products(options: { skip: 0, take: 100 }) { items { slug } totalItems } }"
}

### Page 2
POST http://192.168.0.53:3000/shop-api
Content-Type: application/json

{
  "query": "query GetProductSlugsPage2 { products(options: { skip: 100, take: 100 }) { items { slug } } }"
}

### Page 3
POST http://192.168.0.53:3000/shop-api
Content-Type: application/json

{
  "query": "query GetProductSlugsPage3 { products(options: { skip: 200, take: 100 }) { items { slug } } }"
}





